In [1]:
import numpy as np

In [2]:
# =====================================================================
# INSIALISASI DATA (Model Fisik Braket Mesin)
# =====================================================================
# Matriks Koefisien A
A = np.array([[2.0, 1.0, 1.0],
              [1.0, 3.0, 2.0],
              [3.0, 1.0, 2.0]], dtype=float)

# Vektor Konstanta B (Beban Eksternal dalam kN)
B = np.array([[12.0],
              [17.0],
              [15.0]], dtype=float)

print("Matriks Koefisien A:\n", A)
print("Vektor Beban B:\n", B)
print("-" * 50)

Matriks Koefisien A:
 [[2. 1. 1.]
 [1. 3. 2.]
 [3. 1. 2.]]
Vektor Beban B:
 [[12.]
 [17.]
 [15.]]
--------------------------------------------------


In [3]:
# =====================================================================
# METODE 1: MATRIKS INVERS (X = A^-1 * B)
# =====================================================================
print("\n>>> MEMULAI METODE MATRIKS INVERS <<<")

# Hitung invers dari matriks A
A_invers = np.linalg.inv(A)
print("1. Hasil dari Invers Matriks A:\n", A_invers)

# Kalikan matriks invers dengan vektor B
X_invers = np.dot(A_invers, B)

print("2. Solusi Gaya (F1, F2, F3) dengan Matriks Invers:")
print(f"   F1 = {X_invers[0][0]:.1f} kN")
print(f"   F2 = {X_invers[1][0]:.1f} kN")
print(f"   F3 = {X_invers[2][0]:.1f} kN")
print("-" * 50)


>>> MEMULAI METODE MATRIKS INVERS <<<
1. Hasil dari Invers Matriks A:
 [[ 1.   -0.25 -0.25]
 [ 1.    0.25 -0.75]
 [-2.    0.25  1.25]]
2. Solusi Gaya (F1, F2, F3) dengan Matriks Invers:
   F1 = 4.0 kN
   F2 = 5.0 kN
   F3 = -1.0 kN
--------------------------------------------------


In [4]:
# =====================================================================
# METODE 2: ELIMINASI GAUSS-JORDAN (Manual Row Operations)
# =====================================================================
print("\n>>> MEMULAI METODE GAUSS-JORDAN <<<")

# Membuat Augmented Matrix [A | B] dengan menggabungkan A dan B
# Kita gunakan .copy() agar matriks asli A dan B tidak rusak
augmented = np.hstack((A, B))
n = len(B) # Mengambil jumlah baris (3)

print("1. Augmented Matrix Awal [A|B]:\n", augmented)

# Proses Eliminasi Berdasarkan Algoritma Gauss-Jordan
for i in range(n):
    # Langkah A: Membuat elemen diagonal utama (pivot) menjadi 1
    pivot = augmented[i, i]
    augmented[i] = augmented[i] / pivot
    
    # Langkah B: Menolkan semua elemen di atas dan di bawah pivot tersebut
    for j in range(n):
        if i != j: # Pastikan kita tidak menolkan baris pivot itu sendiri
            faktor_pengali = augmented[j, i]
            # Rumus OBE: Baris_baru = Baris_lama - (Faktor * Baris_Pivot)
            augmented[j] = augmented[j] - (faktor_pengali * augmented[i])

print("2. Augmented Matrix Akhir setelah OBE [I|X]:\n", augmented)

# Mengambil kolom terakhir sebagai solusi X
X_gauss_jordan = augmented[:, n]

print("3. Solusi Gaya (F1, F2, F3) dengan Gauss-Jordan:")
print(f"   F1 = {X_gauss_jordan[0]:.1f} kN")
print(f"   F2 = {X_gauss_jordan[1]:.1f} kN")
print(f"   F3 = {X_gauss_jordan[2]:.1f} kN")


>>> MEMULAI METODE GAUSS-JORDAN <<<
1. Augmented Matrix Awal [A|B]:
 [[ 2.  1.  1. 12.]
 [ 1.  3.  2. 17.]
 [ 3.  1.  2. 15.]]
2. Augmented Matrix Akhir setelah OBE [I|X]:
 [[ 1.  0.  0.  4.]
 [ 0.  1.  0.  5.]
 [ 0.  0.  1. -1.]]
3. Solusi Gaya (F1, F2, F3) dengan Gauss-Jordan:
   F1 = 4.0 kN
   F2 = 5.0 kN
   F3 = -1.0 kN
